# Generated by Django 2.2.8 on 2020-02-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0058_merge_20191206_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPySenseDevice',
            fields=[
            ],
            options={
                'verbose_name': 'PySense Device',
                'verbose_name_plural': 'PySense Devices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='PySenseDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPL3115A2_temperature_active', models.BooleanField(blank=True, default=False)),
                ('MPL3115A2_temperature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable')),
                ('PySense_device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
