# Generated by Django 2.2.8 on 2020-02-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0059_auto_20200211_1049'),
        ('laborenergie', '0002_add_device_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pysensedevice',
            name='MPL3115A2_altitude',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_altitude', to='pyscada.Variable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='MPL3115A2_altitude_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='MPL3115A2_pressure',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_pressure', to='pyscada.Variable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='MPL3115A2_pressure_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='MPL3115A2_temperature',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_temperature', to='pyscada.Variable'),
        ),
    ]
