# Generated by Django 2.2.8 on 2020-02-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0059_auto_20200211_1049'),
        ('laborenergie', '0005_auto_20200219_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='LTR329ALS01_light_active',
            new_name='LTR329ALS01_light_blue_active',
        ),
        migrations.RemoveField(
            model_name='pysensedevice',
            name='LTR329ALS01_light',
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LTR329ALS01_light_blue',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTR329ALS01_light_blue', to='pyscada.Variable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LTR329ALS01_light_red',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTR329ALS01_light_red', to='pyscada.Variable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LTR329ALS01_light_red_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
