# Generated by Django 2.2.8 on 2020-02-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborenergie', '0006_auto_20200219_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='PySense_battery',
            new_name='PySense_battery_voltage',
        ),
    ]
