# Generated by Django 2.2.8 on 2020-02-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborenergie', '0007_auto_20200219_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pysensedevice',
            name='IP_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='PySense_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.Device'),
        ),
    ]
