# Generated by Django 2.2.8 on 2020-02-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0008_auto_20190206_1507'),
        ('laborenergie', '0009_auto_20200219_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='LIS2HH12_acceleration_active',
            new_name='LIS2HH12_acceleration_x_active',
        ),
        migrations.RemoveField(
            model_name='pysensedevice',
            name='IP_address',
        ),
        migrations.RemoveField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration',
        ),
        migrations.RemoveField(
            model_name='pysensedevice',
            name='port',
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration_x',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LIS2HH12_acceleration_x', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration_y',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LIS2HH12_acceleration_y', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration_y_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration_z',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LIS2HH12_acceleration_z', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='LIS2HH12_acceleration_z_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='SI7006A20_humidity_ambient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SI7006A20_humidity_ambient', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='SI7006A20_humidity_ambient_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='fw_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PySense_fw_version', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='fw_version_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='hw_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PySense_hw_version', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='hw_version_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='product_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PySense_product_id', to='modbus.ModbusVariable'),
        ),
        migrations.AddField(
            model_name='pysensedevice',
            name='product_ide_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='LIS2HH12_pitch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LIS2HH12_pitch', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='LIS2HH12_roll',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LIS2HH12_roll', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='LTR329ALS01_light_blue',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTR329ALS01_light_blue', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='LTR329ALS01_light_red',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LTR329ALS01_light_red', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='MPL3115A2_altitude',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_altitude', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='MPL3115A2_pressure',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_pressure', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='MPL3115A2_temperature',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPL3115A2_temperature', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='PySense_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modbus.ModbusDevice'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='SI7006A20_dew_point',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SI7006A20_dew_point', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='SI7006A20_humidity',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SI7006A20_humidity', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='SI7006A20_temperature',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SI7006A20_temperature', to='modbus.ModbusVariable'),
        ),
        migrations.AlterField(
            model_name='pysensedevice',
            name='battery_voltage',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PySense_battery', to='modbus.ModbusVariable'),
        ),
    ]
