# Generated by Django 2.2.8 on 2020-02-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborenergie', '0010_auto_20200226_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='product_ide_active',
            new_name='product_id_active',
        ),
    ]
