# Generated by Django 2.2.8 on 2020-02-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborenergie', '0011_auto_20200227_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='SI7006A20_humidity_ambient',
            new_name='SI7006A20_ambient_humidity',
        ),
        migrations.RenameField(
            model_name='pysensedevice',
            old_name='SI7006A20_humidity_ambient_active',
            new_name='SI7006A20_ambient_humidity_active',
        ),
    ]
