# Generated by Django 2.2.8 on 2020-02-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborenergie', '0012_auto_20200227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pysensedevice',
            name='SI7006A20_ambient_humidity',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SI7006A20_ambient_humidity', to='modbus.ModbusVariable'),
        ),
    ]
